/* Auto-generated by build-tokens.ts — DO NOT EDIT */
/* Generated from tokens/*.json */

export interface ColorToken {
  name: string;
  hex: string;
  desc: string;
}

export interface SpacingToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface RadiusToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface ElevationToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface MotionToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface FontSizeToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface FontFamilyToken {
  name: string;
  value: string;
  desc: string;
  cssVar: string;
}

export interface FontWeightToken {
  name: string;
  value: number;
  cssVar: string;
}

export const COLORS_DARK: ColorToken[] = [
  {
    "name": "brand.primary",
    "hex": "#D4AF37",
    "desc": "Hawk Gold — 主品牌色、Logo、重点强调"
  },
  {
    "name": "brand.primary-light",
    "hex": "#E8D48B",
    "desc": "Hover / 高亮状态"
  },
  {
    "name": "brand.primary-dark",
    "hex": "#B8941E",
    "desc": "按下 / 深层状态"
  },
  {
    "name": "background.primary",
    "hex": "#0A0A0A",
    "desc": "主背景"
  },
  {
    "name": "background.secondary",
    "hex": "#141414",
    "desc": "卡片 / 面板背景"
  },
  {
    "name": "background.tertiary",
    "hex": "#1E1E1E",
    "desc": "悬浮 / 弹窗背景"
  },
  {
    "name": "text.primary",
    "hex": "#EAEAEA",
    "desc": "主文字"
  },
  {
    "name": "text.secondary",
    "hex": "#A0A0A0",
    "desc": "次要文字"
  },
  {
    "name": "text.disabled",
    "hex": "#666666",
    "desc": "禁用状态文字"
  },
  {
    "name": "text.on-primary",
    "hex": "#0A0A0A",
    "desc": "Primary 按钮文字 — 深色在金底上"
  },
  {
    "name": "border.default",
    "hex": "#2A2A2A",
    "desc": "默认边框"
  },
  {
    "name": "border.focus",
    "hex": "#D4AF37",
    "desc": "聚焦状态边框"
  },
  {
    "name": "semantic.success",
    "hex": "#34A853",
    "desc": "成功状态"
  },
  {
    "name": "semantic.warning",
    "hex": "#FBBC05",
    "desc": "警告状态"
  },
  {
    "name": "semantic.error",
    "hex": "#EA4335",
    "desc": "错误状态"
  },
  {
    "name": "semantic.info",
    "hex": "#4285F4",
    "desc": "信息状态"
  }
];

export const COLORS_LIGHT: ColorToken[] = [
  {
    "name": "brand.primary",
    "hex": "#4285F4",
    "desc": "Hawk Blue — 主品牌色、Logo、链接、按钮"
  },
  {
    "name": "brand.primary-light",
    "hex": "#669DF6",
    "desc": "Hover 状态"
  },
  {
    "name": "brand.primary-dark",
    "hex": "#1A73E8",
    "desc": "按下状态"
  },
  {
    "name": "brand.accent-red",
    "hex": "#EA4335",
    "desc": "辅助强调（可选）"
  },
  {
    "name": "brand.accent-yellow",
    "hex": "#FBBC05",
    "desc": "辅助强调（可选）"
  },
  {
    "name": "brand.accent-green",
    "hex": "#34A853",
    "desc": "辅助强调（可选）"
  },
  {
    "name": "background.primary",
    "hex": "#FFFFFF",
    "desc": "主背景"
  },
  {
    "name": "background.secondary",
    "hex": "#F8F9FA",
    "desc": "卡片背景"
  },
  {
    "name": "background.tertiary",
    "hex": "#F1F3F4",
    "desc": "悬浮 / 弹窗背景"
  },
  {
    "name": "text.primary",
    "hex": "#202124",
    "desc": "主文字"
  },
  {
    "name": "text.secondary",
    "hex": "#5F6368",
    "desc": "次要文字"
  },
  {
    "name": "text.disabled",
    "hex": "#9AA0A6",
    "desc": "禁用状态文字"
  },
  {
    "name": "text.on-primary",
    "hex": "#202124",
    "desc": "Primary 按钮文字 — 深色在蓝底上"
  },
  {
    "name": "border.default",
    "hex": "#DADCE0",
    "desc": "默认边框"
  },
  {
    "name": "border.focus",
    "hex": "#4285F4",
    "desc": "聚焦状态边框"
  },
  {
    "name": "semantic.success",
    "hex": "#34A853",
    "desc": "成功状态"
  },
  {
    "name": "semantic.warning",
    "hex": "#FBBC05",
    "desc": "警告状态"
  },
  {
    "name": "semantic.error",
    "hex": "#EA4335",
    "desc": "错误状态"
  },
  {
    "name": "semantic.info",
    "hex": "#4285F4",
    "desc": "信息状态"
  }
];

export const SPACING: SpacingToken[] = [
  {
    "name": "0",
    "value": "0px",
    "cssVar": "--spacing-0"
  },
  {
    "name": "1",
    "value": "4px",
    "cssVar": "--spacing-1"
  },
  {
    "name": "2",
    "value": "8px",
    "cssVar": "--spacing-2"
  },
  {
    "name": "3",
    "value": "12px",
    "cssVar": "--spacing-3"
  },
  {
    "name": "4",
    "value": "16px",
    "cssVar": "--spacing-4"
  },
  {
    "name": "6",
    "value": "24px",
    "cssVar": "--spacing-6"
  },
  {
    "name": "8",
    "value": "32px",
    "cssVar": "--spacing-8"
  },
  {
    "name": "12",
    "value": "48px",
    "cssVar": "--spacing-12"
  },
  {
    "name": "16",
    "value": "64px",
    "cssVar": "--spacing-16"
  },
  {
    "name": "24",
    "value": "96px",
    "cssVar": "--spacing-24"
  },
  {
    "name": "32",
    "value": "128px",
    "cssVar": "--spacing-32"
  }
];

export const RADII: RadiusToken[] = [
  {
    "name": "none",
    "value": "0px",
    "cssVar": "--radius-none"
  },
  {
    "name": "sm",
    "value": "6px",
    "cssVar": "--radius-sm"
  },
  {
    "name": "md",
    "value": "10px",
    "cssVar": "--radius-md"
  },
  {
    "name": "lg",
    "value": "16px",
    "cssVar": "--radius-lg"
  },
  {
    "name": "full",
    "value": "9999px",
    "cssVar": "--radius-full"
  }
];

export const ELEVATIONS: ElevationToken[] = [
  {
    "name": "none",
    "value": "none",
    "cssVar": "--elevation-none"
  },
  {
    "name": "low",
    "value": "0 1px 3px rgba(0,0,0,0.08)",
    "cssVar": "--elevation-low"
  },
  {
    "name": "medium",
    "value": "0 4px 12px rgba(0,0,0,0.12)",
    "cssVar": "--elevation-medium"
  },
  {
    "name": "high",
    "value": "0 8px 24px rgba(0,0,0,0.16)",
    "cssVar": "--elevation-high"
  }
];

export const MOTIONS: MotionToken[] = [
  {
    "name": "instant",
    "value": "0ms",
    "cssVar": "--motion-duration-instant"
  },
  {
    "name": "fast",
    "value": "120ms",
    "cssVar": "--motion-duration-fast"
  },
  {
    "name": "normal",
    "value": "200ms",
    "cssVar": "--motion-duration-normal"
  },
  {
    "name": "slow",
    "value": "320ms",
    "cssVar": "--motion-duration-slow"
  }
];

export const FONT_SIZES: FontSizeToken[] = [
  {
    "name": "xs",
    "value": "0.75rem",
    "cssVar": "--font-size-xs"
  },
  {
    "name": "sm",
    "value": "0.875rem",
    "cssVar": "--font-size-sm"
  },
  {
    "name": "base",
    "value": "1rem",
    "cssVar": "--font-size-base"
  },
  {
    "name": "lg",
    "value": "1.125rem",
    "cssVar": "--font-size-lg"
  },
  {
    "name": "xl",
    "value": "1.25rem",
    "cssVar": "--font-size-xl"
  },
  {
    "name": "2xl",
    "value": "1.5rem",
    "cssVar": "--font-size-2xl"
  },
  {
    "name": "3xl",
    "value": "1.875rem",
    "cssVar": "--font-size-3xl"
  },
  {
    "name": "4xl",
    "value": "2.25rem",
    "cssVar": "--font-size-4xl"
  }
];

export const FONT_FAMILIES: FontFamilyToken[] = [
  {
    "name": "logo",
    "value": "'Plus Jakarta Sans', sans-serif",
    "desc": "Logo / Display — 几何无衬线，直线感（定制/手工调整）",
    "cssVar": "--font-family-logo"
  },
  {
    "name": "heading",
    "value": "'Plus Jakarta Sans', 'Inter', sans-serif",
    "desc": "标题 — 中等字重无衬线",
    "cssVar": "--font-family-heading"
  },
  {
    "name": "body",
    "value": "'Inter', sans-serif",
    "desc": "正文 — 高可读无衬线",
    "cssVar": "--font-family-body"
  },
  {
    "name": "code",
    "value": "'JetBrains Mono', monospace",
    "desc": "代码 — 等宽",
    "cssVar": "--font-family-code"
  }
];

export const FONT_WEIGHTS: FontWeightToken[] = [
  {
    "name": "regular",
    "value": 400,
    "cssVar": "--font-weight-regular"
  },
  {
    "name": "medium",
    "value": 500,
    "cssVar": "--font-weight-medium"
  },
  {
    "name": "semibold",
    "value": 600,
    "cssVar": "--font-weight-semibold"
  },
  {
    "name": "bold",
    "value": 700,
    "cssVar": "--font-weight-bold"
  }
];
