import * as fs from "fs";
import * as path from "path";

interface TokenValue {
  $value: string | number | number[];
  $type: string;
  $description?: string;
}

interface TokenGroup {
  [key: string]: TokenValue | TokenGroup;
}

function flattenTokens(
  obj: TokenGroup,
  prefix = ""
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    const fullKey = prefix ? `${prefix}-${key}` : key;
    if (
      typeof value === "object" &&
      value !== null &&
      "$value" in value
    ) {
      const token = value as TokenValue;
      if (Array.isArray(token.$value)) {
        result[fullKey] = `cubic-bezier(${token.$value.join(", ")})`;
      } else {
        result[fullKey] = String(token.$value);
      }
    } else if (typeof value === "object" && value !== null) {
      Object.assign(result, flattenTokens(value as TokenGroup, fullKey));
    }
  }
  return result;
}

function generateCSS() {
  const tokensDir = path.resolve(__dirname, "../tokens");

  // Read all token files
  const darkColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/dark.json"), "utf-8")
  );
  const lightColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/light.json"), "utf-8")
  );
  const typography = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "typography.json"), "utf-8")
  );
  const spacing = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "spacing.json"), "utf-8")
  );
  const radius = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "radius.json"), "utf-8")
  );
  const motion = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "motion.json"), "utf-8")
  );
  const elevation = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "elevation.json"), "utf-8")
  );
  const breakpoint = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "breakpoint.json"), "utf-8")
  );

  const darkColorVars = flattenTokens(darkColors.color);
  const lightColorVars = flattenTokens(lightColors.color);
  const typographyVars = flattenTokens(typography);
  const spacingVars = flattenTokens(spacing.spacing);
  const radiusVars = flattenTokens(radius.radius);
  const motionDurationVars = flattenTokens(motion.duration);
  const motionEasingVars = flattenTokens(motion.easing);
  const elevationVars = flattenTokens(elevation.elevation);
  const breakpointVars = flattenTokens(breakpoint.breakpoint);

  function varsToCSS(vars: Record<string, string>, indent = "  "): string {
    return Object.entries(vars)
      .map(([key, value]) => `${indent}--${key}: ${value};`)
      .join("\n");
  }

  const css = `/* Auto-generated by build-tokens.ts — DO NOT EDIT */
/* Generated from tokens/*.json */

:root,
[data-theme="light"] {
${varsToCSS(lightColorVars)}
${varsToCSS(typographyVars)}
${varsToCSS(spacingVars)}
${varsToCSS(radiusVars)}
${varsToCSS(motionDurationVars)}
${varsToCSS(motionEasingVars)}
${varsToCSS(elevationVars)}
${varsToCSS(breakpointVars)}
}

[data-theme="dark"] {
${varsToCSS(darkColorVars)}
${varsToCSS(typographyVars)}
${varsToCSS(spacingVars)}
${varsToCSS(radiusVars)}
${varsToCSS(motionDurationVars)}
${varsToCSS(motionEasingVars)}
${varsToCSS(elevationVars)}
${varsToCSS(breakpointVars)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${varsToCSS(darkColorVars)}
  }
}
`;

  const outDir = path.resolve(__dirname, "../src/styles");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(path.join(outDir, "generated-tokens.css"), css);
  console.log("✅ Generated: src/styles/generated-tokens.css");
}

generateCSS();
