import * as fs from "fs";
import * as path from "path";

interface TokenValue {
  $value: string | number | number[];
  $type: string;
  $description?: string;
}

interface TokenGroup {
  [key: string]: TokenValue | TokenGroup;
}

function flattenTokens(
  obj: TokenGroup,
  prefix = ""
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    const fullKey = prefix ? `${prefix}-${key}` : key;
    if (
      typeof value === "object" &&
      value !== null &&
      "$value" in value
    ) {
      const token = value as TokenValue;
      if (Array.isArray(token.$value)) {
        result[fullKey] = `cubic-bezier(${token.$value.join(", ")})`;
      } else {
        result[fullKey] = String(token.$value);
      }
    } else if (typeof value === "object" && value !== null) {
      Object.assign(result, flattenTokens(value as TokenGroup, fullKey));
    }
  }
  return result;
}

function varsToCSS(vars: Record<string, string>, indent = "  "): string {
  return Object.entries(vars)
    .map(([key, value]) => `${indent}--${key}: ${value};`)
    .join("\n");
}

function generateCSS() {
  const tokensDir = path.resolve(__dirname, "../tokens");

  // Read all token files
  const darkColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/dark.json"), "utf-8")
  );
  const lightColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/light.json"), "utf-8")
  );
  const typography = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "typography.json"), "utf-8")
  );
  const spacing = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "spacing.json"), "utf-8")
  );
  const radius = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "radius.json"), "utf-8")
  );
  const motion = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "motion.json"), "utf-8")
  );
  const elevation = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "elevation.json"), "utf-8")
  );
  const breakpoint = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "breakpoint.json"), "utf-8")
  );

  // Flatten with full namespace prefixes
  const darkColorVars = flattenTokens(darkColors.color, "color");
  const lightColorVars = flattenTokens(lightColors.color, "color");

  // Typography: each subgroup gets its own namespace prefix
  const fontFamilyVars = flattenTokens(typography.fontFamily, "font-family");
  const fontSizeVars = flattenTokens(typography.fontSize, "font-size");
  const fontWeightVars = flattenTokens(typography.fontWeight, "font-weight");
  const lineHeightVars = flattenTokens(typography.lineHeight, "line-height");
  const letterSpacingVars = flattenTokens(typography.letterSpacing, "letter-spacing");

  // Spacing, radius, motion, elevation, breakpoint
  const spacingVars = flattenTokens(spacing.spacing, "spacing");
  const radiusVars = flattenTokens(radius.radius, "radius");
  const motionDurationVars = flattenTokens(motion.duration, "motion-duration");
  const motionEasingVars = flattenTokens(motion.easing, "motion-easing");
  const elevationVars = flattenTokens(elevation.elevation, "elevation");
  const breakpointVars = flattenTokens(breakpoint.breakpoint, "breakpoint");

  // Collect all non-color token vars (output once, not duplicated per theme)
  const nonColorVars: Record<string, string> = {
    ...fontFamilyVars,
    ...fontSizeVars,
    ...fontWeightVars,
    ...lineHeightVars,
    ...letterSpacingVars,
    ...spacingVars,
    ...radiusVars,
    ...motionDurationVars,
    ...motionEasingVars,
    ...elevationVars,
    ...breakpointVars,
  };

  // Separate theme-specific colors from shared colors
  const darkOnly: Record<string, string> = {};
  const lightOnly: Record<string, string> = {};
  const sharedColors: Record<string, string> = {};
  
  const allColorKeys = [...Object.keys(darkColorVars), ...Object.keys(lightColorVars)].filter((v, i, a) => a.indexOf(v) === i);
  for (const key of allColorKeys) {
    const darkVal = darkColorVars[key];
    const lightVal = lightColorVars[key];
    if (darkVal === lightVal) {
      sharedColors[key] = darkVal;
    } else {
      if (darkVal) darkOnly[key] = darkVal;
      if (lightVal) lightOnly[key] = lightVal;
    }
  }

  const css = `/* Auto-generated by build-tokens.ts — DO NOT EDIT */
/* Generated from tokens/*.json */

:root,
[data-theme="light"] {
${varsToCSS(lightOnly)}
${varsToCSS(sharedColors)}
${varsToCSS(nonColorVars)}
}

[data-theme="dark"] {
${varsToCSS(darkOnly)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${varsToCSS(darkOnly, "    ")}
  }
}
`;

  const outDir = path.resolve(__dirname, "../src/styles");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(path.join(outDir, "generated-tokens.css"), css);
  console.log("✅ Generated: src/styles/generated-tokens.css");
}

function generateTS() {
  const tokensDir = path.resolve(__dirname, "../tokens");

  const darkColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/dark.json"), "utf-8")
  );
  const lightColors = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "color/light.json"), "utf-8")
  );
  const typography = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "typography.json"), "utf-8")
  );
  const spacing = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "spacing.json"), "utf-8")
  );
  const radius = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "radius.json"), "utf-8")
  );
  const motion = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "motion.json"), "utf-8")
  );
  const elevation = JSON.parse(
    fs.readFileSync(path.join(tokensDir, "elevation.json"), "utf-8")
  );

  // Build color arrays for page.tsx consumption
  function buildColorArray(
    colorData: any,
    mode: string
  ): Array<{ name: string; hex: string; desc: string }> {
    const result: Array<{ name: string; hex: string; desc: string }> = [];
    function walk(obj: any, prefix = "") {
      for (const [key, value] of Object.entries(obj)) {
        if (key.startsWith("$")) continue;
        const fullKey = prefix ? `${prefix}.${key}` : key;
        if (
          typeof value === "object" &&
          value !== null &&
          "$value" in value
        ) {
          const token = value as any;
          result.push({
            name: fullKey,
            hex: String(token.$value),
            desc: token.$description || "",
          });
        } else if (typeof value === "object" && value !== null) {
          walk(value, fullKey);
        }
      }
    }
    walk(colorData.color);
    return result;
  }

  const darkColorArray = buildColorArray(darkColors, "dark");
  const lightColorArray = buildColorArray(lightColors, "light");

  // Build spacing array with namespaced CSS var name
  const spacingArray = Object.entries(spacing.spacing)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      cssVar: `--spacing-${k}`,
    }));

  // Build radius array with namespaced CSS var name
  const radiusArray = Object.entries(radius.radius)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      cssVar: `--radius-${k}`,
    }));

  // Build elevation array with namespaced CSS var name
  const elevationArray = Object.entries(elevation.elevation)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      cssVar: `--elevation-${k}`,
    }));

  // Build motion array with namespaced CSS var name
  const motionArray = Object.entries(motion.duration)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      cssVar: `--motion-duration-${k}`,
    }));

  // Build font arrays with namespaced CSS var names
  const fontSizeArray = Object.entries(typography.fontSize)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      cssVar: `--font-size-${k}`,
    }));

  const fontFamilyArray = Object.entries(typography.fontFamily)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as string,
      desc: (v as any).$description || "",
      cssVar: `--font-family-${k}`,
    }));

  const fontWeightArray = Object.entries(typography.fontWeight)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => ({
      name: k,
      value: (v as any).$value as number,
      cssVar: `--font-weight-${k}`,
    }));

  const ts = `/* Auto-generated by build-tokens.ts — DO NOT EDIT */
/* Generated from tokens/*.json */

export interface ColorToken {
  name: string;
  hex: string;
  desc: string;
}

export interface SpacingToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface RadiusToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface ElevationToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface MotionToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface FontSizeToken {
  name: string;
  value: string;
  cssVar: string;
}

export interface FontFamilyToken {
  name: string;
  value: string;
  desc: string;
  cssVar: string;
}

export interface FontWeightToken {
  name: string;
  value: number;
  cssVar: string;
}

export const COLORS_DARK: ColorToken[] = ${JSON.stringify(darkColorArray, null, 2)};

export const COLORS_LIGHT: ColorToken[] = ${JSON.stringify(lightColorArray, null, 2)};

export const SPACING: SpacingToken[] = ${JSON.stringify(spacingArray, null, 2)};

export const RADII: RadiusToken[] = ${JSON.stringify(radiusArray, null, 2)};

export const ELEVATIONS: ElevationToken[] = ${JSON.stringify(elevationArray, null, 2)};

export const MOTIONS: MotionToken[] = ${JSON.stringify(motionArray, null, 2)};

export const FONT_SIZES: FontSizeToken[] = ${JSON.stringify(fontSizeArray, null, 2)};

export const FONT_FAMILIES: FontFamilyToken[] = ${JSON.stringify(fontFamilyArray, null, 2)};

export const FONT_WEIGHTS: FontWeightToken[] = ${JSON.stringify(fontWeightArray, null, 2)};
`;

  const outDir = path.resolve(__dirname, "../src/lib");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(path.join(outDir, "generated-token-data.ts"), ts);
  console.log("✅ Generated: src/lib/generated-token-data.ts");
}

generateCSS();
generateTS();
